const authors = [
  "A.P. Carter",
  "Billy Simon",
  "Bob Dylan",
  "Brían Mac Gloinn",
  "Carrie B. Adams",
  "Charles K. Harris",
  "Dan Emmett",
  "David Coffin",
  "Delmore Brothers",
  "Dick Gaughan",
  "Dick Holler",
  "Don McClean",
  "Donal Lunny",
  "Dougie MacLean",
  "Ewan MacColl",
  "Francis D. Henry",
  "Fred Rose",
  "George W. Young",
  "Gordon Lightfoot",
  "Harry Dacre",
  "Harry McClintock",
  "Idris Davies and Pete Seeger",
  "Irving Berlin",
  "James Chadwick",
  "Jimmy Driftwood",
  "Jimmy MacCarthy",
  "John Ceiriog Hughes",
  "John Francis Wade",
  "John Newton",
  "John Prine",
  "Leonard Cohen",
  "Martin Luther",
  "Michael Scanlan",
  "Mississippi John Hurt",
  "Patrick Joseph McCall",
  "Paul Siebel",
  "Paul Simon",
  "Peggy Seeger and Ewan MacColl",
  "Phil Ochs",
  "Richard Thompson",
  "Robert Burns",
  "Si Kahn",
  "Stan Rogers",
  "Stephen Foster",
  "Thomas Moore",
  "Tom Paxton",
  "Wayne Carson",
  "William Douglas",
  "Woody Guthrie",
  "Ye Vagabonds",
  "Unknown"
];
